### ISSUE TITLE
Atualização para lucene 8.x

### ISSUE THREAD

**Issue by viniciusandrade** [bireme/iahx-analyzer#4]
Heitor, 

Quando possível, favor verificar a viabilidade de atualização do código dos analizadores para a versão atual do lucene para que possamos planejar a atualização do Solr.

Obrigado

**Comment by heitorbarbieri** [comment]
Elaborando melhor a ideia anterior imaginemos um documento que fosse indexado utilizando-se todas as heurísticas atuais, isto é, indexado como fazemos hoje, mas que na hora da recuperação, o usuário poderia ao fazer uma pesquisa avançada checar as heurísticas que quisesse por exemplo, "utilizar sinônimos do DeCS", "especificar o idioma da expressão de busca", "utilizar variações quando duas palavras estão unidas por hífen", etc.

O analizador da indexação gera todas as possibilidades de variações do documento mas o analizador de pesquisa receberia um parâmetro de configuração que geraria a expressão de busca conforme as heurísticas escolhidas pelo usuário. Se o usuário não seleciona nenhuma heurística a expressão de busca se comportaria como uma expressão do lucene "pura".

Implementando assim, saberíamos na maioiria dos casos explicar o porquê de cada documento recuperado, gerando assim uma transparência que não temos atualmente no iahx.

**Comment by viniciusandrade** [comment]
Issue encerrado devido a disponibilidade da versão 9 do Lucene.
